######################################################################
# Automatically generated by qmake (3.0) ?? 7? 17 07:51:49 2017
######################################################################
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = GoToCell

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
